title: SKG-IF documentation
description: SKG-IF documentation
theme: just-the-docs

url: https://skg-if.github.io

nav_external_links:
  - title: Interoperability Framework 
    url: https://skg-if.github.io/interoperability-framework/
    hide_icon: true
  - title: JSON-LD context
    url: https://skg-if.github.io/context/
    hide_icon: true
  - title: Examples 
    url: https://skg-if.github.io/examples/
    hide_icon: true
  - title: Extensions
    url: https://skg-if.github.io/extensions/
    hide_icon: true
  - title: Snapshot
    url: https://skg-if.github.io/snapshot/
    hide_icon: true
  - title: API
    url: https://skg-if.github.io/api/
    hide_icon: true